import { NativeModules } from 'react-native'

export enum Ssdk {
  DEVICE_NOT_SUPPORTED = NativeModules.Ssdk.DEVICE_NOT_SUPPORTED,
  LIBRARY_NOT_INSTALLED = NativeModules.Ssdk.LIBRARY_NOT_INSTALLED,
  LIBRARY_UPDATE_IS_RECOMMENDED = NativeModules.Ssdk.LIBRARY_UPDATE_IS_RECOMMENDED,
  LIBRARY_UPDATE_IS_REQUIRED = NativeModules.Ssdk.LIBRARY_UPDATE_IS_REQUIRED,
  VENDOR_NOT_SUPPORTED = NativeModules.Ssdk.VENDOR_NOT_SUPPORTED,
}
